### ISSUE TITLE
lineage.microg.org doesnt have latest ota

### ISSUE THREAD

**Issue by TjrGithub** [microg/microg.org#20]
Hi, when comparing the downloads section of lineageos.org and lineage.microg.org, I've noticed the mido device is missing the 20190522 ota update. Additionally, the lineageos updater APP complains that it cannot find the ota Website (which used to work).

**Comment by ale5000-git** [comment]
Your message has nothing to do with the main website (this repository is for the main webiste).

You should write here for the LineageOS for microG builds: https://github.com/lineageos4microg/docker-lineage-cicd
And here for the LineageOS for microG website: https://github.com/lineageos4microg/l4m_website

**Comment by TjrGithub** [comment]
Fixed in https://github.com/lineageos4microg/l4m_website/issues/31
