### ISSUE TITLE
Realme phones missing

### ISSUE THREAD

**Issue by tuxayo** [microg/microg.org#28]
https://download.lineageos.org/RMX1801
https://download.lineageos.org/RMX1851

https://download.lineage.microg.org/RMX1801/
https://download.lineage.microg.org/RMX1851/

**Comment by tuxayo** [comment]
IIUC any phone that has official LineageOS support should have automatically have a LineageOS for microG version.

**Comment by sorryusernameisalreadytaken** [comment]
@tuxayo I think you can close this, right?

RMX1801 got a monthly build and RMX1851 had no officially build anymore.

**Comment by tuxayo** [comment]
Correct! :)
