### ISSUE TITLE
F-Droid repo QRcode image 404 error

### ISSUE THREAD

**Issue by ChipZhang** [microg/microg.org#42]
**Describe the bug**
F-Droid repo QRcode image 404 error

**To Reproduce**
1. Open the webpage: https://microg.org/fdroid.html
2. The repo's QRcode image does not display properly
3. Inspect the page, only find that the [image's link](https://chart.googleapis.com/chart?cht=qr&chl=https%3A%2F%2Fmicrog.org%2Ffdroid%2Frepo%3Ffingerprint%3D9BD06727E62796C0130EB6DAB39B73157451582CBD138E86C468ACC395D14165&chs=256x256&choe=UTF-8&chld=L|0) is 404 error.

**Expected behavior**
A qrcode image should display in the page.

**Screenshots**
![image](https://github.com/microg/microg.org/assets/11641178/80d3e3d6-bcf3-44ca-b186-dfe57eeacf20)

**Comment by mar-v-in** [comment]
Fixed.
