### ISSUE TITLE
microg.org down since 2016-11-05

### ISSUE THREAD

**Issue by quatauta** [microg/microg.org#6]
Since Sat 5 Nov 2016, microg.org and its F-Droid repository is down for me.

http://currentlydown.com/microg.org

**Comment by mar-v-in** [comment]
Yes, the server has hardware issues, it will hopefully be fixed on Monday, Wednesday latest.

**Comment by mar-v-in** [comment]
Server should be up again. Seems like one of the RAID hard drives is broken. The server will be offline again for a few hours on Wednesday.

**Comment by mar-v-in** [comment]
hard drive replaced.
